# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_SAMPLE_RUST_I2C_CLIENT)		+= rust_i2c_client.o
obj-$(CONFIG_SAMPLE_RUST_MINIMAL)		+= rust_minimal.o
obj-$(CONFIG_SAMPLE_RUST_PRINT)			+= rust_print.o

subdir-$(CONFIG_SAMPLE_RUST_HOSTPROGS)		+= hostprogs
